---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-de
spec:
  replicas: 4
  selector: 
    matchLables:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      name: jenkins-pod
      lables:
        app: jenkins
        version: 1.609.2
    spec:
      containers:
        - image: jenkins:1.609.2
          name: jenkins1
          ports: 
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"